server:
  port: 80

spring:
  profiles:
    active: prod

s3Client:
  auth:
    basicAuth:
      userName: yD=r@Z@pQ\&.rnU+2bQm>T:A/>Fdj@S]
      password: 7N%bdEfE-SUSQ43;_aty2Y}SF4z[(qnm
  cors:
    allowedOrigins: "*"
  configs:
    UNJ_API_S3_CONNECTION_TIMEOUT: 10000ms
    UNJ_API_S3_REQUEST_TIMEOUT: 0
    UNJ_API_S3_SOCKET_TIMEOUT: 50000ms
    UNJ_API_S3_MAX_POOL_CONNECTION: 50
    UNJ_API_S3_MAX_IDLE_MILLIS: 60000ms
    UNJ_API_S3_CONNECTION_TTL: -1
